FROM python:3.9-slim

WORKDIR /app

RUN pip install sentence-transformers

COPY requirements.txt .

RUN apt-get update && apt-get install -y \
    libpq-dev \
    libpq5 \
    gcc \
    # Clean up apt-get cache to reduce image size
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip 

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
